### ISSUE TITLE
FOUC issue 

### ISSUE THREAD

**Issue by IsaacHub** [AshotAleqs/ng-zorro-switch-theme#2]
While switching between themes, default browser style is getting applied and that looks ugly for 1 second, which is know as `flash of unstyled content`, is there any way to fix this?

**Comment by AshotAleqs** [comment]
Hello @IsaacHub,

Thanks for reporting, the issue is fixed and pushed to the master.

**Comment by IsaacHub** [comment]
Thanks for the update.
However I went for the css variable approach:
https://stackblitz.com/edit/dark-mode-with-angular-and-css-variables-4bjhu3
